### ISSUE TITLE
Fallos en descargas de ficheros externos 

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree-backend#17]
Cuando se crean despliegues externos y el fichero que debe de bajarse del repositorio externo es grande, en el cliente aparece el mensaje **esperando cabeceras** produciéndose un error si se sobrepasa cierto tiempo.

Cambio propuesto: Descargar el fichero el segundo plano y **redirigir** la petición a la url remota si el fichero local no existe.

**Comment by agacias** [comment]
**Redirigir** la petición a la url remota no es adecuado porque el cliente puede no tener acceso a internet.

Por favor @jact Incorpora los cambios desde la versión 4  migasfree/migasfree#305

**Comment by jact** [comment]
https://github.com/migasfree/migasfree-backend/commit/521ab9e4be50860e6baa18fe5a1128980b6767dd
